name: Update README

on:
  workflow_dispatch:

jobs:
  activity:
    name: Update README with recent activity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Add activity to readme
        uses: Readme-Workflows/recent-activity@add-whitelist-feature
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
