name: Update README

on:
  workflow_dispatch:

jobs:
  activity:
    name: Update README with recent activity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Add activity to template
        uses: Readme-Workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Readme replacer
        uses: Readme-Workflows/readme-replacer@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
